"""add_missing_blog_columns

Revision ID: 21bd278b8532
Revises: fedb1eb983d6
Create Date: 2026-01-30 11:34:21.636117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21bd278b8532'
down_revision: Union[str, None] = 'fedb1eb983d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_contact_enquiries_id', table_name='contact_enquiries')
    # op.drop_table('contact_enquiries')
    # op.drop_index('ix_meta_leads_id', table_name='meta_leads')
    # op.drop_index('lead_id', table_name='meta_leads')
    # op.drop_table('meta_leads')
    # op.drop_index('client_id', table_name='meta_credentials')
    # op.drop_index('ix_meta_credentials_id', table_name='meta_credentials')
    # op.drop_table('meta_credentials')
    # op.drop_index('campaign_id', table_name='meta_campaigns')
    # op.drop_index('ix_meta_campaigns_id', table_name='meta_campaigns')
    # op.drop_table('meta_campaigns')
    # op.drop_index('ix_career_applications_id', table_name='career_applications')
    # op.drop_table('career_applications')
    op.add_column('blogs', sa.Column('banner_image', sa.String(length=500), nullable=True))
    op.add_column('blogs', sa.Column('banner_title', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('sections', sa.JSON(), nullable=True))
    op.add_column('blogs', sa.Column('blog_date', sa.DateTime(), nullable=True))
    op.add_column('blogs', sa.Column('read_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'read_time')
    op.drop_column('blogs', 'blog_date')
    op.drop_column('blogs', 'sections')
    op.drop_column('blogs', 'banner_title')
    op.drop_column('blogs', 'banner_image')
    op.create_table('career_applications',
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('position_applied', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('experience_years', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_company', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('portfolio_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('linkedin_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('resume_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cover_letter', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_career_applications_id', 'career_applications', ['id'], unique=False)
    op.create_table('meta_campaigns',
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('objective', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('daily_budget', mysql.FLOAT(), nullable=True),
    sa.Column('lifetime_budget', mysql.FLOAT(), nullable=True),
    sa.Column('spend', mysql.FLOAT(), nullable=True),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('stop_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='meta_campaigns_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_meta_campaigns_id', 'meta_campaigns', ['id'], unique=False)
    op.create_index('campaign_id', 'meta_campaigns', ['campaign_id'], unique=True)
    op.create_table('meta_credentials',
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ad_account_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('access_token', mysql.TEXT(), nullable=False),
    sa.Column('app_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('app_secret', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='meta_credentials_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_meta_credentials_id', 'meta_credentials', ['id'], unique=False)
    op.create_index('client_id', 'meta_credentials', ['client_id'], unique=True)
    op.create_table('meta_leads',
    sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lead_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('form_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_time', mysql.DATETIME(), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('raw_data', mysql.JSON(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['meta_campaigns.id'], name='meta_leads_ibfk_2'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='meta_leads_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('lead_id', 'meta_leads', ['lead_id'], unique=True)
    op.create_index('ix_meta_leads_id', 'meta_leads', ['id'], unique=False)
    op.create_table('contact_enquiries',
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_contact_enquiries_id', 'contact_enquiries', ['id'], unique=False)
    # ### end Alembic commands ###
