"""add image alt text columns

Revision ID: f78f3e739a8c
Revises: 21bd278b8532
Create Date: 2026-01-30 14:12:14.563287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f78f3e739a8c'
down_revision: Union[str, None] = '21bd278b8532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns to blogs
    op.add_column('blogs', sa.Column('banner_image_alt', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('featured_image_alt', sa.String(length=255), nullable=True))
    
    # Add columns to case_studies
    op.add_column('case_studies', sa.Column('featured_image_alt', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_studies', 'featured_image_alt')
    op.drop_column('blogs', 'featured_image_alt')
    op.drop_column('blogs', 'banner_image_alt')
    # ### end Alembic commands ###
